### ISSUE TITLE
[[Question]] Capability to Send Files?

### ISSUE THREAD

**Issue by 4tuw2tuv0** [DarrenN/simple-http#2]
Admittedly, I don't have any real experience sending HTTP calls with files so I may be missing something that should be otherwise readily apparent.

I was looking through the documentation and didn't see any examples so I wondering how it might be feasible to send a file in, say, a POST request.

For full disclosure, I'm working from Python where the command is just

```Python
requests.post(url,
              headers=headers,
              data=json.dumps(post_data),
              files=files,
              timeout=timeout,
              proxies=proxies)
```

**Comment by DarrenN** [comment]
Good question, I don't regularly upload files so haven't considered this case. From this SO question it looks like you need to assemble the boundaries and bytes for the POST body: https://stackoverflow.com/questions/34672542/racket-upload-zip-file-with-parameters-through-http-client-or-post-impure-port

**Comment by 4tuw2tuv0** [comment]
Ugh; alright, that'll take some digging around, on my part. Thanks a ton; and thanks for this library: from what I've played with, it's really stable and definitely really easy to navigate and understand. It's been a lot of fun to work with and really helpful.

Two last questions I'd forgotten 'til now: is there any support for timeouts and proxies, like in the Python code? The timeout bit isn't terribly important to me but the proxy bit I am particularly interested in getting working.

**Comment by DarrenN** [comment]
I don't really know what the proxies is? (not familiar with the Python.) 

If you need specific feature support you might consider rolling with [net/url](https://docs.racket-lang.org/net/url.html?q=net%2Furl#%28part._.U.R.L_.Functions%29) functions directly or [http/request](https://docs.racket-lang.org/http/index.html?q=http) - they give you a lot of control. `http/request` will let you setup timeouts on a connection pool. If using `net/url` you could probably wire something up using [`sync/timeout`](https://docs.racket-lang.org/reference/sync.html?q=sync%2Ftimeout#%28def._%28%28quote._~23~25kernel%29._sync%2Ftimeout%29%29) and a thread.

This lib was mostly to slap together basic requests for hitting JSON and XML APIs. I've been thinking about doing a big refactor on it lately after working on some other things.

**Comment by 4tuw2tuv0** [comment]
Totally fair; I guess proxies in HTTP requests (I've yet to've used them, myself, so I'm not particularly familiar, either).

Mmm; O. K. Yours was one of the first that popped up when I searched something like "racket get request" so I hadn't seen those. Thanks a ton.

I'm gonna close this since you've addressed all my question. Thanks, again; I really appreciate it and your responses helped a lot.
