### ISSUE TITLE
Communicating through a unix socket

### ISSUE THREAD

**Issue by pmatos** [DarrenN/simple-http#4]
Is there a way to make a request through a unix socket?

Something along the lines of (using curl):
```
$ curl --unix-socket /var/run/docker.sock http://localhost/containers/json
[]
``` 

I tried:
```racket
(define docker-sock
  (update-host json-requester "/var/run/docker.sock"))

(define response (get docker-sock "/containers/json"))
```

But got back
```
; tcp-connect: connection failed;
;  host not found
;   address: /var/run/docker.sock
;   port number: 80
;   system error: Name or service not known; gai_err=-2
; Context:
;  /home/pmatos/installs/racket-6.12/collects/net/http-client.rkt:65:0 http-conn-open!10
;  /home/pmatos/installs/racket-6.12/collects/net/http-client.rkt:394:0 http-sendrecv105
;  /home/pmatos/.racket/6.12/pkgs/simple-http/main.rkt:274:7 get19
;  /home/pmatos/Projects/s10-tryout/src/docker.rkt:1:1 [running body]
; [Due to errors, REPL is just module language, requires, and stub definitions]
```

**Comment by pmatos** [comment]
I guess instead of using `tcp-connect` one could call `unix-socket-connect`?

**Comment by DarrenN** [comment]
Hi there -

So, [under the hood](https://github.com/DarrenN/simple-http/blob/master/main.rkt#L280) I'm using [http-sendrecv](https://docs.racket-lang.org/net/http-client.html?q=http-sendrecv#%28def._%28%28lib._net%2Fhttp-client..rkt%29._http-sendrecv%29%29), which as you can imagine is pretty specific about wanting to make a web request in a certain fashion. I don't really know much about unix sockets, but in general it seems like it would be a big change to add this feature.

**Comment by juniorxxue** [comment]
> Is there a way to make a request through a unix socket?
> 
> Something along the lines of (using curl):
> 
> ```
> $ curl --unix-socket /var/run/docker.sock http://localhost/containers/json
> []
> ```
> 
> I tried:
> 
> ```racket
> (define docker-sock
>   (update-host json-requester "/var/run/docker.sock"))
> 
> (define response (get docker-sock "/containers/json"))
> ```
> 
> But got back
> 
> ```
> ; tcp-connect: connection failed;
> ;  host not found
> ;   address: /var/run/docker.sock
> ;   port number: 80
> ;   system error: Name or service not known; gai_err=-2
> ; Context:
> ;  /home/pmatos/installs/racket-6.12/collects/net/http-client.rkt:65:0 http-conn-open!10
> ;  /home/pmatos/installs/racket-6.12/collects/net/http-client.rkt:394:0 http-sendrecv105
> ;  /home/pmatos/.racket/6.12/pkgs/simple-http/main.rkt:274:7 get19
> ;  /home/pmatos/Projects/s10-tryout/src/docker.rkt:1:1 [running body]
> ; [Due to errors, REPL is just module language, requires, and stub definitions]
> ```

Hi, do you find any workaround to connect to unix socket?
so far I use `socat` to handle docker remote api
and use `simple-http` to normally request
detailed info: https://forums.docker.com/t/remote-api-with-docker-for-mac-beta/15639

**Comment by pmatos** [comment]
@xuuexu Sorry - found nothing. In the meantime, I had forgotten about this. Closing given it's not relevant for me anymore.

**Comment by DarrenN** [comment]
@xuuexu you might want to take a look at `racket/tcp` https://docs.racket-lang.org/reference/tcp.html and perhaps create a `simple-tcp` or perhaps PR something up to this package that adds that feature.
