### ISSUE TITLE
Allow setting port

### ISSUE THREAD

**Issue by spenceforce** [DarrenN/simple-http#5]
http-sendrecv defaults to 80. It would be awesome if this was configurable to allow non default ports.

I can make a pull request when I have some time this week.

**Comment by DarrenN** [comment]
Hello!

Looks like `http-sendrecv` can take a `#:port` keyword so it should be pretty straightforward to add that feature in. If you could put together a PR that would be great.

**Comment by spenceforce** [comment]
Awesome, in terms of design I was thinking of adding an optional parameter for update-host, but creating an update-port function is another option. Do you have a preference?

Something like:
`(define (update-host req nhost [port #f]) ...)`

**Comment by DarrenN** [comment]
Let's make an `update-port` function - keeps with the spirit of `update-headers`, `update-ssl`, etc.

Thanks for working on this!

**Comment by DarrenN** [comment]
Fixed in #6
